name: "GitHub Issue Summarizer"
description: "Automatically summarize long GitHub issues when /summarize-issue is commented"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to authenticate and interact with the GitHub API"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key to access the GPT-powered summarizer"
    required: true
  prompt_template_path:
    description: "Path to the prompt template file"
    required: false
    default: "templates/prompt_template.txt"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: "main"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Cache poetry virtualenv
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run summarizer
      run: poetry run python src/main.py "${{ github.event.repository.full_name }}" "${{ github.event.issue.number }}" "${{ github.event.comment.id }}" "${{ inputs.GITHUB_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
